M48
; DRILL file {KiCad 9.0.0} date 2026-02-16T12:18:10+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-16T12:18:10+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.302
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X133.0Y-52.01
X133.0Y-77.0
X133.0Y-89.0
X133.0Y-113.99
T2
X131.0Y-43.0
X131.0Y-123.0
X192.0Y-43.0
X192.0Y-123.0
M30
